version: "3.8"

services:
  server:
    build: server/
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
    volumes:
      - ./server:/app
      - /var/projects/fernando/nodejs/socket-io-chat/server/node_modules

  client:
    build: client/
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - ./client:/app
      - /var/projects/fernando/nodejs/socket-io-chat/client/node_modules
    depends_on:
      - server
